const fakeData = [
    {
      orderID: 1,
      orderNumber: "Order001",
      orderDate: "2023-06-01",
      customerName: "Customer A",
      phoneNumber: "123456789",
      email: "customerA@example.com",
      productID: "Prod001",
      productName: "Product X",
      quantity: 1,
      productType: "Type A",
      deliveryMethod: "Courier",
      batchID: "Batch001",
    },
    {
      orderID: 2,
      orderNumber: "Order002",
      orderDate: "2023-06-02",
      customerName: "Customer B",
      phoneNumber: "987654321",
      email: "customerB@example.com",
      productID: "Prod002",
      productName: "Product Y",
      quantity: 2,
      productType: "Type B",
      deliveryMethod: "Postal",
      batchID: "Batch002",
    },
    {
      orderID: 3,
      orderNumber: "Order003",
      orderDate: "2023-06-03",
      customerName: "Customer C",
      phoneNumber: "555666777",
      email: "customerC@example.com",
      productID: "Prod003",
      productName: "Product Z",
      quantity: 3,
      productType: "Type C",
      deliveryMethod: "Courier",
      batchID: "Batch003",
    },
  ];

  export default fakeData;